wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.12
    framework: huggingface
    huggingface_version: 4.34.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1698637442.719995
    t:
      1:
      - 1
      - 5
      - 11
      - 12
      - 41
      - 49
      - 53
      - 55
      - 75
      2:
      - 1
      - 5
      - 11
      - 12
      - 41
      - 49
      - 53
      - 55
      - 75
      3:
      - 1
      - 2
      - 13
      - 19
      - 23
      4: 3.10.12
      5: 0.15.12
      6: 4.34.1
      8:
      - 1
      - 5
      - 12
      13: linux-x86_64
batch_size:
  desc: null
  value: 32
test_batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 40
lr:
  desc: null
  value: 0.01
momentum:
  desc: null
  value: 0.5
no_cuda:
  desc: null
  value: false
log_interval:
  desc: null
  value: 10
